'use client';
import {sitePath} from '@/lib/site-path';
import {useState} from 'react';
import {cases,modes} from '@/lib/cases';
import {comparisonPanels} from '@/lib/comparison-panels.mjs';
import {Slide} from './slide';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
export function Gallery(){const [scale,setScale]=useState('all'),[mode,setMode]=useState('All failure modes');const shown=cases.filter(c=>(scale==='all'||c.scale===scale)&&(mode==='All failure modes'||c.mode===mode));return <section id="gallery" aria-label="Before and better gallery"><Tabs value={scale} onValueChange={v=>setScale(String(v))}><div className="gallery-controls">{cases.some(c=>c.scale==='talk')&&<TabsList variant="line" className="gallery-tabs"><TabsTrigger value="all">All cases <span>{cases.length}</span></TabsTrigger><TabsTrigger value="slide">Single slides <span>{cases.filter(c=>c.scale==='slide').length}</span></TabsTrigger><TabsTrigger value="talk">Deck outlines <span>{cases.filter(c=>c.scale==='talk').length}</span></TabsTrigger></TabsList>}<Select value={mode} onValueChange={v=>setMode(v||'All failure modes')}><SelectTrigger className="mode-select" aria-label="Filter by failure mode"><SelectValue/></SelectTrigger><SelectContent>{modes.map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select></div>{['all','slide','talk'].map(s=><TabsContent key={s} value={s}><p className="results-count" aria-live="polite">{shown.length} {shown.length===1?'case':'cases'} · {mode==='All failure modes'?'Before and after slide comparisons':mode}</p><div className="gallery-grid">{shown.map(c=>{const pair=comparisonPanels(c);const firstAfter=pair.after[0];const firstBefore=pair.before[0];return <a className="gallery-card" key={c.id} href={sitePath(`/case/${c.id}`)}><div className="card-art"><div className="mini-pair"><div><p className="frame-label">BEFORE</p><Slide panel={firstBefore} variant="before"/></div><div><p className="frame-label better-label">BETTER</p><Slide panel={firstAfter}/></div></div><span className="card-arrow" aria-hidden="true">↗</span></div><div className="card-info"><div className="card-topline"><span>{c.number} / {c.mode}</span><span>{c.topic}{c.scale==='talk'?' · OUTLINE':''}</span></div><h2>{c.title}</h2><p>{c.dek}</p><div className="card-source"><span className={`source-dot ${c.sourceType}`}/>{c.sourceType==='public'?c.source!.authors+' · '+c.source!.date:'Constructed teaching example'}<span className="case-link">Explore →</span></div></div></a>})}</div>{!shown.length&&<div className="no-results"><h2>No cases in this combination.</h2><button onClick={()=>{setMode('All failure modes');setScale('all')}}>Show all cases</button></div>}</TabsContent>)}</Tabs></section>}
