import content from './gallery-data.json';
export type Panel = {id?:string;revises?:string[];provenance?:string;kind?:string;title:string;sourcePage?:string;label?:string;lines?:string[];formula?:string;note?:string;image?:string;alt?:string;stage?:number;cue?:string;items?:{title:string;text:string}[]};
export type ViewerPanel = Panel & {pages?:string};
export type OutlineStage = {id?:string;revises?:string[];label:string;title:string;content:string;shortTitle?:string;schema?:{title:string;text:string}[];panels?:Panel[];pages?:string;takeaway?:string;role?:'setup'|'result'|'bridge'|'reserve'};
export type DeckOutline = {title:string;overviewTitle?:string;description:string;before:OutlineStage[];after:OutlineStage[];change:string;branches?:{fromStage:number;returnToStage:number;title:string;pages:string;content:string}[]};
export type Case = {id:string;number:string;title:string;topic?:string;point?:string;mode:string;scale:'slide'|'talk';sourceType:'public'|'constructed';outline?:DeckOutline;dek:string;before:Panel[];after:Panel[];diagnosis:string;changes:string[];preserved:string;deferred:string;practice:string;principle:string;source?:{authors:string;title:string;date:string;url:string;pages:string};context:string;beforeCaption:string;afterCaption:string;values?:string[]};
export const cases=content as Case[];
export const modes=['All failure modes','Buried takeaway','Hidden question','Notation overload','Generality first','Visual overload','Table search','No re-entry','Mandatory detour','Detached caveats'];
export const principleAnchors:Record<string,string>={'Give the audience a direction':'give-the-audience-a-direction','Takeaways before details':'takeaways-before-details','Give people a way back in':'give-people-a-way-back-in','Choose detail that carries insight':'choose-detail-that-carries-insight','Let the slide unfold':'let-the-slide-unfold','Minimize tables with lots of numbers!':'minimize-tables-with-lots-of-numbers','Set deadlines and adjust as you go':'set-deadlines-and-adjust-as-you-go','Be bigger than your paper':'be-bigger-than-your-paper'};
